In [1]:
import os, sys
import os.path as osp

import pandas as pd

In [2]:
BASE_DIR = os.getcwd()
FILENAME = "COPDGene_P1P2P3_Flat_SM_NS_Sep23interim.parquet"

In [4]:
df = pd.read_parquet(FILENAME)

In [5]:
df

,sid_object,gender_category,race_category,Age_P2_float,BMI_P2_float,ATS_PackYears_P2_float,smoking_status_P2_category,neutrophl_P2_float,lymphcyt_P2_float,eosinphl_P2_float,...,LAMA,ICS,LABA_only_category,LAMA_only_category,ICS_only_category,LABA_LAMA_category,LABA_ICS_category,LAMA_ICS_category,LABA_LAMA_ICS_category,COPD_inhaler_tx_category
0,10002K,Female,White,70.7,NaN,45.0,Ex-smoker,NaN,NaN,NaN,...,True,True,F,F,F,F,F,F,T,LABA_LAMA_ICS
1,10004O,Male,White,NaN,NaN,NaN,None,NaN,NaN,NaN,...,None,None,F,F,F,F,F,F,F,no_tx
2,10005Q,Female,White,60.0,27.37,45.5,Smoker,3.80,2.60,0.10,...,None,False,F,F,F,F,F,F,F,no_tx
3,10006S,Female,White,68.0,33.34,52.0,Ex-smoker,3.76,1.96,0.15,...,True,True,F,F,F,F,F,F,T,LABA_LAMA_ICS
4,10008W,Male,White,NaN,NaN,NaN,None,NaN,NaN,NaN,...,None,None,F,F,F,F,F,F,F,no_tx
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10300,26180S,Female,Black,63.2,NaN,45.1,Ex-smoker,NaN,NaN,NaN,...,None,False,F,F,F,F,F,F,F,no_tx
10301,26181U,Male,Black,NaN,NaN,NaN,None,NaN,NaN,NaN,...,None,None,F,F,F,F,F,F,F,no_tx
10302,26182W,Female,Black,NaN,NaN,NaN,None,NaN,NaN,NaN,...,None,None,F,F,F,F,F,F,F,no_tx
10303,26183Y,Male,Black,52.2,32.82,23.6,Smoker,4.60,2.60,0.40,...,False,True,F,F,F,F,T,F,F,LABA_ICS
10304,26185C,Male,Black,58.0,26.39,13.5,Ex-smoker,5.90,1.10,0.10,...,False,False,F,F,F,F,F,F,F,no_tx

In [7]:
df["neutr_lymph_ratio_P2_float"] = df["neutrophl_P2_float"] / df["lymphcyt_P2_float"]

In [ ]:
# df.dtypes

cols = [
        "sid_object",
        "gender_category", 
        "Age_P2_float", 
        "BMI_P2_float", 
        "Exacerbation_Frequency_P2_category", 
        "ATS_PackYears_P2_float",
        "smoking_status_P2_category",
        "eosinphl_P2_float",
        "neutr_lymph_ratio_P2_float"
        ]

In [9]:
df = df[cols]

In [10]:
df

,gender_category,Age_P2_float,BMI_P2_float,Exacerbation_Frequency_P2_category,ATS_PackYears_P2_float,smoking_status_P2_category,eosinphl_P2_float,neutr_lymph_ratio_P2_float
0,Female,70.7,NaN,1,45.0,Ex-smoker,NaN,NaN
1,Male,NaN,NaN,None,NaN,None,NaN,NaN
2,Female,60.0,27.37,0,45.5,Smoker,0.10,1.461538
3,Female,68.0,33.34,2,52.0,Ex-smoker,0.15,1.918367
4,Male,NaN,NaN,None,NaN,None,NaN,NaN
...,...,...,...,...,...,...,...,...
10300,Female,63.2,NaN,None,45.1,Ex-smoker,NaN,NaN
10301,Male,NaN,NaN,None,NaN,None,NaN,NaN
10302,Female,NaN,NaN,None,NaN,None,NaN,NaN
10303,Male,52.2,32.82,0,23.6,Smoker,0.40,1.769231
10304,Male,58.0,26.39,0,13.5,Ex-smoker,0.10,5.363636